import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero/Hero';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/footer/footer';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';
import { Services } from '../utils/Services';
import Nav from '../components/Navbar/Nav';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Avenue 25</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        

        {/* cards */}

        
      </Layout>
    </div>
  );
}
