import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero/Hero';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/footer/footer';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';
import { Services }from '../utils/Services'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Avenue 25</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <Hero />

          {/* cards */}

          <div className={styles.cards}>


            <div className={styles.cardArea}>
              <div className={styles.cardContiner}>
                  {Services.map((service, i) => {
                    return(
                      <div className={styles.card} key={i}>
                        <h4
                          className={styles.avatar} id={service.id}
                        >
                            {service.title}
                        </h4>
                        <h2 className={styles.cardTitle}>{service.name}</h2> 
                        <p
                          className={styles.cardText}
                        >
                          Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam voluptatum harum culpa, officiis non Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        </p>
                        <a
                          className={styles.cardLink}
                        >
                          Learn More
                        </a>
                      </div>
                    )
                  })}
              </div> 
            </div>
          </div>

          {/* About */}

          <div className={styles.about}>
              <div className={styles.aboutContainer}>
                <div className={styles.aboutText}>
                  <h2>What we are About !</h2>
                  <p> We are a medium sized digital agency focused on niched services, We pride ourselves in resuts more than anything and client satisfaction is our main goal, we have been in the business for more than  years and we are slowly carving our footprints to the sand and becoming one of the most prefared agencies. We believe that every business should have at least one of the services we offer, for visibility and brand positioning thats why we help connect, protect and put businesses online.
                  let us helpwith all of your digital needs whatever the size 
                
                  </p>
                  
                </div>
                <div className={styles.aboutImage}>
                  <Image src="/Img/6308.jpg" height={2100} width={3400} />
                </div>
              </div>
          </div>

          <div className={styles.banner}>
            <div className={styles.bannerContainer}>
                <div className={styles.bannerText}>
                  <h5>Lets get the ball rolling</h5>
                  <h3>Lets have a chat about how we can increase <br />your digital footprint and <br /> Improve business</h3>
                  <a href=""> Call us </a>
                </div>
            </div>
          </div>

      </Layout>
    </div>
  )
}
